# Generated by Django 3.0.8 on 2020-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(help_text='link to mem', max_length=20)),
                ('text', models.CharField(help_text='text mem', max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
