# Generated by Django 3.0.8 on 2020-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='name tag', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mem',
            name='tags',
            field=models.ManyToManyField(help_text='tags mem', to='storage.tag'),
        ),
    ]
