# Generated by Django 3.0.8 on 2020-07-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20200710_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='text',
            field=models.CharField(help_text='text mem', max_length=200),
        ),
    ]
